#!/usr/bin/env perl

use v5.42;
use strictures 2;

use Test::More;

use_ok('AoC::Solution::Day7');

my $solution = AoC::Solution::Day7->new(
    input => join("\n", q(
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    )),
);

is($solution->part_1, 21, 'part_1');
is($solution->part_2, 40, 'part_2');

done_testing();
